dist: bionic
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T test_ci_cd-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ushebdim:$BINTRAY_API_KEY "https://api.bintray.com/mariasopkova/test_ci_cd/ci_cd_package/$TRAVIS_BUILD_NUMBER/test_ci_cd-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
